rules:
  disable_join_messages: false
  disable_quit_messages: false
  disable_death_messages: false

spawn:
  world: world
  x: 0.5
  y: 100
  z: 0.5
  yaw: 0
  pitch: 0

# Here you can customize the player's inventory
# As the key, put the slot and as the value use an item from the 'items' config
inventory:
  4: teleporter

# Available options (with their required types):
# label      - The item's name
# type       - The action type (none, server, page)
# material   - The item's material type
# enchanted  - If the item should glimmer
# permission - The permission required to see the item
# lore       - A string list listing the item lore
# server     - To what server the item should send you (requires 'server' type)
# page       - To what teleporter page the item should send you (requires 'page' type)

# Here you can build items which are used in guis or in the hotbar
# For the item name you have to edit the translation files.
# If you have an item named 'teleporter', the translation key would be 'lobby.items.teleporter'
# An item consits out of the following properties:
# - material  - The item material.                            Default: dirt
# - enchanted - If the item should glow.                      Default: false
# - action    - What should happen when clicking on the item. Default: none
#   - none:    Nothing happens
#   - server:  Connects the player to a BungeeCord subserver.
#   - gui:     Opens a different gui from the 'gui' config
# - value     - The value for specific 'action' values.       Default: ''
#   - action 'none':    You can omit this property
#   - action 'server':  Put the name of the internal BungeeCord server
#   - action 'gui':     Put the gui name which should be opened
items:
  filler:
    material: gray_stained_glass_pane
  teleporter:
    material: compass
    enchanted: true
    action: gui
    value: teleporter
  back_teleporter:
    material: arrow
    action: gui
    value: teleporter
  server_soon:
    material: barrier
    enchanted: false
    action: none
  server_citybuild:
    material: grass_block
    enchanted: true
    action: server
    value: citybuild-1
  server_staff:
    material: compass
    permission: lobby.page.team
    enchanted: true
    action: gui
    value: teleporter_staff

# This is an array of menus. Each menu can have a filler and has to specify an amount of rows
# The filler is basically put into all slots which are omitted in this config. To not use a filler, put 'none'
# For each slot just use the number as the key and an item from the 'items' config as the value
# For the gui name you have to edit the translation files.
# If you have a gui named 'teleporter', the translation key would be 'lobby.guis.teleporter'
guis:
  teleporter:
    rows: 3
    filler: filler
    slots:
      12: soon
      14: server_citybuild
      16: soon
      27: server_staff
  teleporter_staff:
    rows: 3
    filler: filler
    slots:
      19: back_teleporter