name: Lobby
version: '${project.version}'
main: com.rappytv.lobby.LobbyPlugin
api-version: '1.20'
depend:
  - RyLib

commands:
  lobby:
    permission: lobby.reload

permissions:
  lobby.*:
    default: op
    children:
      lobby.reload:
        default: op

      lobby.block.place:
        default: op
      lobby.block.break:
        default: op
      lobby.item.move:
        default: op
      lobby.item.pickup:
        default: op
      lobby.item.drop:
        default: op
      lobby.attack:
        default: op

      lobby.gui.hopper:
        default: op

      lobby.page.default:
        default: true
      lobby.page.*:
        default: op